name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Setup PHP
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: mbstring, bcmath, intl, pdo_sqlite
        coverage: none

    # Setup Node.js untuk Tailwind + Vite
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install PHP Dependencies
      run: composer install --no-interaction --no-progress --prefer-dist

    - name: Install Node Dependencies
      run: npm install

    - name: Build Assets (Vite + Tailwind)
      run: npm run build

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Set Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Run Tests (Unit & Feature)
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test
